name: Check Style
concurrency: # Cancel currently running style checks when a new one is started
  group: style-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

jobs:
  checkStyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Detekt
        run: ./gradlew detekt

      - name: Upload detekt SARIF files
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'build/reports/detekt/merge.sarif'
          category: detekt