name: KMM Bridge Publish Release
on:
  push:
    branches:
      - develop
      - main

jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.7
    secrets:
      gradle_params: "-PGITHUB_BRANCH=${{ github.ref_name }}"
