name: Publish Android
on:
  push:
    branches:
      - main
      - develop

jobs:
  publish:
    if: ${{ !contains(github.event.head_commit.message, 'no publish') }} # TODO needed?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Extract keystore
        run: |
          cd androidApp
          echo "${{ secrets.KEYS_TAR_ASC }}" > .keys.tar.gz.asc
          gpg -d --passphrase "${{ secrets.KEYS_PASSPHRASE }}" --batch .keys.tar.gz.asc > .keys.tar.gz
          tar xzf .keys.tar.gz
          cd ..

      - name: Release Android
        if: ${{ github.ref_name == 'main' }}
        run: ./gradlew publishProdReleaseApps --no-daemon -PkeyPassword=${{ secrets.KEY_PASSWORD }} -PstorePassword=${{ secrets.STORE_PASSWORD }}
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Release Android Lava
        if: ${{ github.ref_name == 'develop' }}
        run: ./gradlew publishLavaReleaseApps --no-daemon -PkeyPassword=${{ secrets.KEY_PASSWORD }} -PstorePassword=${{ secrets.STORE_PASSWORD }}
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Create prod version tag
        if: ${{ github.ref_name == 'main' }}
        run: git tag android-$(cat androidApp/build/prodRelease.version)

      - name: Create lava version tag
        if: ${{ github.ref_name == 'develop' }}
        run: git tag android-$(cat androidApp/build/lavaRelease.version)

      - name: Push version tag
        run: git push --tags

      # TODO auto increase androidPatch in version.properties and push (to dev, add "(no publish)" to commit to prevent publishing (see job if))?

      # TODO add discord or other notification