name: Publish Android Lava
concurrency:
  group: publish-android-lava
  cancel-in-progress: true

on:
  workflow_dispatch:
    branches:
      - develop
  push:
    branches:
      - develop
    paths:
      - 'androidApp/**'
      - '!androidApp/version.properties'
      - 'buildSrc/**'
      - 'gradle/**'
      - 'shared/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'

jobs:
  publish-android-lava:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract keystore
        run: |
          cd androidApp
          echo "${{ secrets.KEYS_TAR_ASC }}" > .keys.tar.gz.asc
          gpg -d --passphrase "${{ secrets.KEYS_PASSPHRASE }}" --batch .keys.tar.gz.asc > .keys.tar.gz
          tar xzf .keys.tar.gz
          cd ..

      - name: Release Android Lava
        run: ./gradlew publishLavaReleaseApps --no-daemon -PkeyPassword=${{ secrets.KEY_PASSWORD }} -PstorePassword=${{ secrets.STORE_PASSWORD }}
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Add version to env
        run: |
          ANDROID_VERSION=$(cat androidApp/build/version.tag)
          echo "ANDROID_VERSION=${ANDROID_VERSION}" >> $GITHUB_ENV
          echo "VERSION_TAG=android/${ANDROID_VERSION}" >> $GITHUB_ENV

      - name: Create version tag ${{ env.VERSION_TAG }}
        run: |
          git tag ${{ env.VERSION_TAG }}
          git push origin ${{ env.VERSION_TAG }}

      # TODO send a notification?