name: Publish Android Prod
concurrency:
  group: publish-android-prod
  cancel-in-progress: true

on:
  push:
    tags:
      - 'android/*.*.*'
      - '!android/*.*.*-*'

jobs:
  publish-android-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract keystore
        run: |
          cd androidApp
          echo "${{ secrets.KEYS_TAR_ASC }}" > .keys.tar.gz.asc
          gpg -d --passphrase "${{ secrets.KEYS_PASSPHRASE }}" --batch .keys.tar.gz.asc > .keys.tar.gz
          tar xzf .keys.tar.gz
          cd ..

      - name: Release Android Prod
        run: ./gradlew publishProdReleaseApps --no-daemon -PkeyPassword=${{ secrets.KEY_PASSWORD }} -PstorePassword=${{ secrets.STORE_PASSWORD }}
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Add version to env
        run: |
          ANDROID_VERSION=$(cat androidApp/build/version.tag)
          echo "ANDROID_VERSION=${ANDROID_VERSION}" >> $GITHUB_ENV
          echo "VERSION_TAG=android/${ANDROID_VERSION}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Android ${{ env.ANDROID_VERSION }}
          tag_name: ${{ env.VERSION_TAG }}
          prerelease: true # As the release is not yet available on the Play Store
          generate_release_notes: true

      # TODO add notification?
