name: Publish
concurrency: # Cancel currently running releases when a new one is started
  group: publish-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    branches:
      - develop
      - main
    inputs:
      androidOnly:
        type: boolean
        description: Release android only
        default: false
  push:
    branches:
      - develop
      - main
    paths:
      - 'androidApp/**'
      - '!androidApp/version.properties'
      - 'shared/**'
      - 'buildSrc/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'

jobs:
  changes:
    name: Identify changed modules
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.changes.outputs.android }}
      shared: ${{ steps.changes.outputs.shared }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |
            android:
              - 'androidApp/**'
            shared:
              - 'shared/**'
              - 'buildSrc/**'
              - 'build.gradle.kts'
              - 'gradle.properties'
              - 'settings.gradle.kts'

  release-shared:
    name: Release shared
    permissions:
      contents: write
      packages: write
    needs: changes
    if: ${{ (github.event_name != 'workflow_dispatch' && needs.changes.outputs.shared == 'true') || (github.event_name == 'workflow_dispatch' && !github.event.inputs.androidOnly) }}
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@v1.1
    with:
      jvmVersion: 17
      versionBaseProperty: SHARED_BASE_VERSION
      # kmmBridgePublish = xcFramework, publishAndroidReleasePublicationToGitHubPackagesRepository = Android lib
      publishTask: kmmBridgePublish publishAndroidReleasePublicationToGitHubPackagesRepository
    secrets:
      gradle_params: "-PGITHUB_BRANCH=${{ github.ref_name }}"


  android-after-shared:
    name: Release Android
    needs: release-shared
    uses: ./.github/workflows/publishAndroid.yml
    secrets: inherit

  android-only:
    name: Release Android only
    needs: changes
    if: ${{ (needs.changes.outputs.android == 'true' && needs.changes.outputs.shared == 'false') || (github.event_name == 'workflow_dispatch' && github.event.inputs.androidOnly) }}
    uses: ./.github/workflows/publishAndroid.yml
    secrets: inherit
