name: Test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest # use mac so that shared iOS targets can also be built
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Test shared
        run: ./gradlew shared:test --stacktrace

      - name: Test android
        run: ./gradlew androidApp:test --stacktrace