name: Test
concurrency: # Cancel currently running tests when a new one is started
  group: test-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches-ignore:
      - 'build-**' # temporary build branch for kmmbridge
    paths:
      - 'androidApp/**'
      - '!androidApp/version.properties'
      - 'shared/**'
      - 'buildSrc/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: macos-latest # use mac so that shared iOS targets can also be built
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Cache kotlin native build tooling
        uses: actions/cache@v4
        with:
          path: "~/.konan"
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}

      - name: Test shared
        run: ./gradlew shared:test --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Test android
        run: ./gradlew androidApp:test --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"