name: Test
on:
  push:
    branches-ignore:
      - 'build-**' # temporary build branch for kmmbridge

jobs:
  test:
    runs-on: macos-latest # use mac so that shared iOS targets can also be built
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache kotlin native build tooling
        uses: actions/cache@v3
        with:
          path: "~/.konan"
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}

      - name: Test shared
        run: ./gradlew shared:test --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Test android
        run: ./gradlew androidApp:test --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"